.TH GODEP "1" "August 2010" "GoMake 0.2.4" "Golang Programmer's Toolset"
.SH NAME
godep \- dependency resolver for golang
.SH SYNOPSIS
.B godep
[\fIoptions\fR] [\fISOURCEFILE [...]\fR]
.SH DESCRIPTION
Create from the specified golang source files, or (if no arguments are given)
all golang source files in the current directory, a dependency tree for use
in makefiles.

The dependency tree output by \fBgodep\fR may be include'd into a makefile, 
or further processed by \fBgomake\fR(1) to yield a complete working makefile.

If no arguments are given, \fBgodep\fR will search the current directory for
all files with an extension of ".go", and assume them to be go source files.
The output of \fBgodep\fR assumes that the \fIO\fR has been set within the
Makefile.

Note that \fBgodep\fR will only resolve dependencies within a project.

.SH OPTIONS
.TP
\fB\-\-version\fR
display version information and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
display help screen and exit
\fB\-n\fR, \fB\-\-need\fR
display unresolvable dependencies
.SH BUGS
Current bugs can be viewed in the issue tracker on github
<http://github.com/bytbox/gomake/issues>. Bugs and feature requests may be
reported to the same place.
.SH SEE ALSO
\fBgomake\fR(1), \fBgorules\fR(1), \fBgoinfo\fR(1)
.SH AUTHOR
Written by Scott Lawrence <bytbox@gmail.com>
.SH COPYRIGHT
Copyright 2010 The Go Authors. All rights reserved.
.br
Use of this source code is governed by a BSD-style
.br
license that can be found in the LICENSE file.