.TH GOINFO "1" "August 2010" "GoMake 0.2.4" "Golang Programmer's Toolset"
.SH NAME
goinfo \- print info about golang project
.SH SYNOPSIS
.B goinfo
[\fIoptions\fR] [\fISOURCEFILE [...]\fR] > Makefile.info
.SH DESCRIPTION
Print meta-info about a Golang project in a Makefile-compatible format.
.SH OPTIONS
.TP
\fB\-\-version\fR
display version information and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
display help screen and exit
.SH BUGS
Current bugs can be viewed in the issue tracker on github
<http://github.com/bytbox/gomake/issues>. Bugs and feature requests may be
reported to the same place.
.SH SEE ALSO
\fBgodep\fR(1), \fBgorules\fR(1), \fBgomake\fR(1)
.SH AUTHOR
Written by Scott Lawrence <bytbox@gmail.com>
.SH COPYRIGHT
Copyright 2010 The Go Authors. All rights reserved.
.br
Use of this source code is governed by a BSD-style
.br
license that can be found in the LICENSE file.